facemask_shop/editor/urls.py
from django.urls import path

from facemask_shop.editor.views import upload_facemask

app_name = 'editor'
urlpatterns = [
    path('upload/', upload_facemask, name='upload'),
]

facemask_shop/editor/models.py
import os
from io import BytesIO

from PIL import Image, ImageCms
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db import models

RESOURCE_DIR = os.path.join(os.path.dirname(__file__), 'resources/')
MASK_WIDTH_PX = 1680
MASK_HEIGHT_PX = 945
MASK_THUMBNAIL_WIDTH_PX = 160
MASK_THUMBNAIL_HEIGHT_PX = 90
MASK_IMAGE_PATH = os.path.join(RESOURCE_DIR, 'mask_image_mask.png')
PROFILE_RGB_ADOBE = os.path.join(RESOURCE_DIR, 'icc_profiles/RGB/AdobeRGB1998.icc')
PROFILE_CMYK_US_WEB_COATED = os.path.join(RESOURCE_DIR, 'icc_profiles/CMYK/USWebCoatedSWOP.icc')


class Facemask(models.Model):
    # The image, with a mesh applied, from the PlayCanvas editor
    full_image = models.ImageField(upload_to='facemask/full_image/')
    # The image uploaded or captured by the user, no mesh applied
    original_image = models.ImageField(upload_to='facemask/original_image/', blank=True, null=True)
    # A thumbnail of the mask_image
    thumbnail = models.ImageField(upload_to='facemask/thumbnail/', blank=True, null=True)

    # The image, resized and with mask applied
    mask_image = models.ImageField(upload_to='facemask/mask_image/', blank=True, null=True)

    def get_profile_or_default(self, image: Image.Image) -> ImageCms.ImageCmsProfile:
        input_profile_str = image.info.get('icc_profile')
        if input_profile_str:
            input_profile = BytesIO(input_profile_str)
            return ImageCms.ImageCmsProfile(input_profile)
        else:
            return ImageCms.ImageCmsProfile(PROFILE_RGB_ADOBE)

    def create_mask_image(self, override=False):
        if self.mask_image and not override:
            return False
        full_image = Image.open(self.full_image)
        # Resize
        mask_sized_image = full_image.resize((MASK_WIDTH_PX, MASK_HEIGHT_PX))
        # Apply mask
        mask_image = Image.open(MASK_IMAGE_PATH)
        mask_sized_image.paste(mask_image, (0, 0), mask_image)
        # Profile conversion
        input_profile = self.get_profile_or_default(mask_sized_image)
        mask_sized_image_cmyk = ImageCms.profileToProfile(mask_sized_image, inputProfile=input_profile, outputProfile=PROFILE_CMYK_US_WEB_COATED, outputMode='CMYK')
        # Save to mask_image
        mask_image_buffer = BytesIO()
        mask_sized_image_cmyk.save(fp=mask_image_buffer, format='JPEG')

        mask_image_name = 'mask_image_%s.jpg' % (self.id,)
        self.mask_image = SimpleUploadedFile(mask_image_name, mask_image_buffer.getvalue(), 'image/jpeg')
        self.save()

    def create_thumbnail(self, override=False):
        if self.thumbnail and not override:
            return False
        self.create_mask_image(override)

        mask_image = Image.open(self.mask_image)
        thumbnail_image = mask_image.resize((MASK_THUMBNAIL_WIDTH_PX, MASK_THUMBNAIL_HEIGHT_PX))

        thumbnail_image_buffer = BytesIO()
        thumbnail_image.save(fp=thumbnail_image_buffer, format='JPEG')

        thumbnail_image_name = 'thumbnail_image_%s.jpg' % (self.id,)
        self.thumbnail = SimpleUploadedFile(thumbnail_image_name, thumbnail_image_buffer.getvalue(), 'image/jpeg')
        self.save()

facemask_shop/editor/forms.py
from django import forms

from facemask_shop.editor.models import Facemask


class FacemaskForm(forms.ModelForm):
    class Meta:
        model = Facemask
        fields = forms.ALL_FIELDS

facemask_shop/editor/views.py
from django.http import JsonResponse, HttpResponseNotAllowed, HttpResponse
from django.views.decorators.csrf import csrf_exempt

from facemask_shop.editor.forms import FacemaskForm


@csrf_exempt
def upload_facemask(request):
    if request.method == 'OPTIONS':
        response = HttpResponse()
        response['Access-Control-Allow-Origin'] = '*'
        response['Access-Control-Allow-Headers'] = ', '.join((
            "accept",
            "accept-encoding",
            "authorization",
            "content-type",
            "dnt",
            "origin",
            "user-agent",
            "x-csrftoken",
            "x-requested-with",
        ))
        response['Access-Control-Allow-Methods'] = 'POST,OPTIONS'
        return response
    if request.method == 'POST':
        form = FacemaskForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            facemask = form.save()
            response = JsonResponse({'success': True, 'mask_id': facemask.id})
        else:
            response = JsonResponse({'success': False, 'errors': form.errors}, status=400)
        response['Access-Control-Allow-Origin'] = '*'
        return response
    return HttpResponseNotAllowed(permitted_methods=('POST',))

facemask_shop/editor/templates/oscar/catalogue/detail-for-class-facemask.html
{% extends "oscar/catalogue/detail.html" %}
{% load i18n %}
{% load static %}

{% comment %}
Disable a lot of blocks here
{% endcomment %}
{% block breadcrumbs %}{% endblock %}
{% block product_info %}{% endblock %}


{% block product_gallery %}
<div class="col-sm-6">
    <div id="product_gallery" class="carousel">
        <div class="thumbnail">
            <div class="carousel-inner">
                <div class="item active">
                    <div id="facemask-editor"></div>
                </div>
            </div>
        </div>
        {% if product.id == products.own_design.id %}
        <ol>
            <li><input type="file" id="fileUploadInput" class="filestyle" data-input="false" data-buttonText="Kies een afbeelding" data-badge="false"></li>
            <li><button id="rotateImageButton" class="btn btn-default"><span class="glyphicon glyphicon-repeat" aria-hidden="true"></span> Roteer beeld</button></li>
            <li>Verschuif de afbeelding op de juiste plaats met je vinger of muis</li>
            <li><button id="toggleRotationButton" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden="true"></span> Looks good?</button> Bestellen maar! Begin anders opnieuw bij 1</li>
        </ol>
        {% endif %}
        {% if product.id == products.selfie.id %}
        <ol>
            <li><button id="handleSelfieButton" class="btn btn-default"><span class="glyphicon glyphicon-facetime-video" aria-hidden="true"></span> Start camera</button></li>
            <li><button id="switchCameraButton" class="btn btn-default" disabled><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Wissel camera</button></li>
            <li>Zet je neus en mond op de juiste plaats</li>
            <li><button id="captureSelfieButton" class="btn btn-default" disabled><span class="glyphicon glyphicon-record" aria-hidden="true"></span> Leg foto vast</button></li>
            <li><button id="toggleRotationButton" class="btn btn-default"><span class="glyphicon glyphicon-play" aria-hidden="true"></span> Looks good?</button> Bestellen maar! Begin anders opnieuw bij 1</li>
        </ol>
        {% endif %}
        <p class="text-center"><a class="btn btn-info" href="https://nl.surveymonkey.com/r/FaceMasksAreCool">Lukt er iets niet? Laat het ons weten!</a></p>
    </div>
</div>
{% endblock %}

{% block product_basket_form %}
{{ block.super }}
{% include "oscar/basket/partials/basket_quick.html" %}
{% comment %}
{% block mini_basket %}{% include "oscar/partials/mini_basket.html" %}{% endblock %}
{% endcomment %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
{% static "editor/playcanvas/16/" as pc_prefix %}
<script src="{{ pc_prefix }}playcanvas-stable.min.js"></script>
<script>
ASSET_PREFIX = "{{ pc_prefix }}";
SCRIPT_PREFIX = "{{ pc_prefix }}";
SCENE_PATH = "916290.json";
CONTEXT_OPTIONS = {
    'antialias': true,
    'alpha': false,
    'preserveDrawingBuffer': false,
    'preferWebGl2': true
};
SCRIPTS = [ 31158195, 31131722, 30592936, 30620114, 30628754, 30803527, 30842522, 30932427, 30980131, 30981096, 30989281, 30989768, 30996399, 31153188 ];
CONFIG_FILENAME = "{{ pc_prefix }}config.json";
INPUT_SETTINGS = {
    useKeyboard: true,
    useMouse: true,
    useGamepads: false,
    useTouch: true
};
pc.script.legacy = false;
PRELOAD_MODULES = [
];
EDITOR_UPLOAD_URL = '{% url 'editor:upload' %}';
</script>
{% endblock %}

{% block extrastyles %}
{{ block.super }}
{% static "editor/playcanvas/16/" as pc_prefix %}
<link rel="stylesheet" href="{{ pc_prefix }}styles.css" />
<style>
/* Empty block for PlayCanvas */

.glyphicon {
    font-family: "Glyphicons Halflings" !important;
}

.bootstrap-filestyle {
    display: inline-block;
}

@media only screen and (max-width : 500px) {
    #product_gallery .thumbnail {
        margin-right: -10%;
        margin-left: -10%;
    }
}

video {
    width: 100%;
}
</style>
{% endblock %}

{% block extrascripts %}
{{ block.super }}
{% static "editor/playcanvas/16/" as pc_prefix %}
<script src="{{ pc_prefix }}__start__.js"></script>
<script src="{% static "editor/js/bootstrap-filestyle.min.js" %}"></script>
<script>
var facemask_editor_canvas = document.getElementById('application-canvas');
document.getElementById('facemask-editor').appendChild(facemask_editor_canvas);

var app = pc.Application.getApplication();
app.on("start", function () {
    $('#add_to_basket_form').on('submit', function(e) {
        e.preventDefault();

        var orderForm = this;

        uploadFile(EDITOR_UPLOAD_URL, function(err, response) {
            if (!err && response.success) {
                $('#id_mask-image-id').val(response.mask_id);
                orderForm.submit();
            } else {
                if (window.Sentry) {
                    if (err instanceof Error) {
                        Sentry.captureException(err);
                    } else {
                        Sentry.captureMessage(err);
                    }
                }
                console.error(err || response);
                alert("Oeps, er ging iets mis bij het opslaan van je masker! Probeer het later opnieuw.");
            }
        });
    });

    $('#fileUploadInput').on('change', handleImageInputChange);
    $('#toggleRotationButton').on('click', toggleRotation).on('click', function() {
        $(this).children('.glyphicon')
            .toggleClass('glyphicon-play', !shouldRotate)
            .toggleClass('glyphicon-pause', shouldRotate);
    });
    $('#rotateImageButton').on('click', rotateImage);
    $('#handleSelfieButton, #switchCameraButton')
        .on('click', function() {
            if (window.facingMode === 'user') {
                window.facingMode = 'environment';
            } else {
                window.facingMode = 'user';
            }
        })
        .on('click', handleSelfie)
        .on('click', function() {
            $('#captureSelfieButton').prop('disabled', false);
            $('#switchCameraButton').prop('disabled', false);
        });
    $('#captureSelfieButton').on('click', captureSelfie);
});
</script>
{% endblock %}